# P-Post n8n Workflow Configuration Example
# Copy this file to config.yaml and update with your values

# Telegram Configuration
telegram:
  bot_token: "YOUR_BOT_TOKEN_HERE"
  chat_id: "YOUR_CHAT_ID_HERE"
  
# Reddit Configuration  
reddit:
  subreddit: "GOONED"
  limit: 30                    # Number of posts to fetch
  rate_seconds: 45            # Delay between posts
  
# Memory Management
memory:
  ttl_days: 60                # How long to remember posted content
  
# Video Processing
video:
  timeout: 120                # Download timeout in seconds
  max_size_mb: 50             # Maximum video size for Telegram
  temp_dir: "/tmp"            # Temporary directory for processing
  
# Logging
logging:
  level: "INFO"               # Log level (DEBUG, INFO, WARN, ERROR)
  file: "p-post.log"          # Log file path
  
# Advanced Settings
advanced:
  retry_attempts: 3           # Number of retry attempts for failed operations
  cleanup_on_error: true      # Clean up temporary files on error
  validate_media: true        # Validate media before posting
